name: "버그 수정"
description: "발견된 버그를 수정합니다"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "버그 설명"
      description: "어떤 문제가 발생하는지 설명"
      placeholder: "BigDecimal 연산 시 scale 누락으로 정산 금액이 부정확하게 산출됨"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "재현 경로"
      description: "버그를 재현하는 단계"
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "기대 동작"
      description: "정상적으로 동작해야 하는 방식"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "실제 동작"
      description: "현재 발생하는 문제 (에러 메시지, 스택 트레이스 포함)"
    validations:
      required: true

  - type: textarea
    id: fix
    attributes:
      label: "수정 방안"
      description: "예상되는 원인과 수정 방향"
    validations:
      required: false

  - type: dropdown
    id: domain
    attributes:
      label: "도메인"
      options:
        - member (회원/인증)
        - owner (업주)
        - order (주문)
        - reward (보상금)
        - settle (지급)
        - frontend (Vue)
        - global (공통)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "우선순위"
      options:
        - "high (서비스 불가)"
        - "medium (기능 오류)"
        - "low (사소한 문제)"
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: "관련 Issue"
      placeholder: "관련 Issue: #"
    validations:
      required: false
